### ISSUE TITLE
remove junglegrass mod 

### ISSUE THREAD

**Issue by Niklp09** [mt-mods/plantlife_modpack#16]
I think it's time to finally remove the Junglegrass mod after more than 8 years. Surely after this long time no world will contain the old blocks anymore.

**Comment by wsor4035** [comment]
at least according to https://content.minetest.net/metapackages/junglegrass/ this would be safe

**Comment by wsor4035** [comment]
granted, its literally hurting nothing by exists, aside from making reserving the modname

**Comment by S-S-X** [comment]
If you ask from me just add PR for deletion. Basically removed 2013 and there's really no reason to "save" this stuff anywhere.
