### ISSUE TITLE
Typo in /bushes/mod.conf

### ISSUE THREAD

**Issue by axcore** [mt-mods/plantlife_modpack#17]
`optional_depends = stonage, sumpf`

I think that should be `stoneage`, especially since init.lua contains the code

`biome_lib.register_on_generate({
		surface = {
			"default:dirt_with_grass",
			"stoneage:grass_with_silex",
			"sumpf:peat",
			"sumpf:sumpf"
		},
		rarity = bushes_bush_rarity,
		rarity_fertility = bushes_bush_rarity_fertility,
		plantlife_limit = bushes_bush_fertility,
		min_elevation = 1, -- above sea level
	},
	abstract_bushes.grow_bush
)`

**Comment by OgelGames** [comment]
You're correct, thanks 👍
