### ISSUE TITLE
fruitless bushes

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/plantlife_modpack#18]
read: https://content.minetest.net/threads/2742/

```
The bushes_classic mod does not function properly, it always spawns fruitless bushes, when I place them.
And I have waited hours for it to fruit but it does not. Plus the bushes cannot be harvested
until bottom node was broken. I have reported this as a thread because issue tracker does not work.
```

**Comment by wsor4035** [comment]
```
Oh I did not and not to forget this is the latest release of this modpack. And only gooseberry bush does not grow rest everyone grows
```

**Comment by MidnightPhantom** [comment]
No, when I planted all of them in a new world gooseberry bush was the first one to grow. I know the mod is a little bugged up. And I dunno how to fix it.

**Comment by fluxionary** [comment]
bushes take a *long* time to regenerate fruit sometimes, but i think they always do eventually.

**Comment by Niklp09** [comment]
Same as https://github.com/mt-mods/plantlife_modpack/issues/19#issuecomment-1646221476.

> it always spawns fruitless bushes, when I place them.

Added bonemeal support, this behavior is intended by the mod.
