### ISSUE TITLE
Bushes_classic mod gives errors

### ISSUE THREAD

**Issue by MidnightPhantom** [mt-mods/plantlife_modpack#19]
None of the bushes form bushes_classic mod generates in my world. When I bonemeal any of the woodsoil no bush ever spawns on it. Then the time which a bush takes to regrow fruits is insane. Please reduce the time and fix the glitch of bushes not spawning.

**Comment by BuckarooBanzay** [comment]
> When I bonemeal any of the woodsoil no bush ever spawns on it

afaik: the bushes from `bushes_classic` aren't "bonemealable" (no mod dependency on it)

No sure about your other issues though :shrug:

**Comment by MidnightPhantom** [comment]
But still the bushes dunno spawn naturally.

**Comment by axcore** [comment]
`biome_lib.register_active_spawner({
	spawn_delay = 3600,
})`

As far as I understand, these bushes do not spawn immediately like most plants do. And they are also quite rare. I do so them occasionally on my v5.5.1 v7 world.

**Comment by Niklp09** [comment]
Everything works as expected, re-open if needed.

> afaik: the bushes from bushes_classic aren't "bonemealable" (no mod dependency on it)

I'll create a PR for this tomorrow

**Comment by Niklp09** [comment]
bonemeal PR https://notabug.org/TenPlus1/bonemeal/pulls/31
