### ISSUE TITLE
Imaginary node: default:water

### ISSUE THREAD

**Issue by axcore** [mt-mods/plantlife_modpack#23]
https://github.com/mt-mods/plantlife_modpack/blob/master/dryplants/reedmace.lua refers to a node called `default:water` which, as far as I can tell, doesn't exist in `default` even as an alias.

Possibly it should be `default:water_source`, which is referenced a few lines later.

**Comment by OgelGames** [comment]
If you mean this: https://github.com/mt-mods/plantlife_modpack/blob/244d5da0e290dadb0c17a955b45bdf7ea4ba2153/dryplants/reedmace.lua#L282-L285
I think it's to match both `default:water_source` *and* `default:water_flowing`.

**Comment by axcore** [comment]
Oh dear, somehow I didn't notice the `string.find`. 

Just forget that you ever saw this post.
