### ISSUE TITLE
Small naming incosistencies

### ISSUE THREAD

**Issue by jolesh** [mt-mods/plantlife_modpack#35]
At least in the template.txt's are some naming incositencies, maybe the templates are just out dated idk.
I know this isn't very important but I just wanted to let you know in case you didn't notice.

### Numbering

in trunks:
`Twigs Roof Corner 1`
`Twigs Roof Corner 2`

in dryplants:
`Reed Roof Corner`
`Reed Roof Corner 2`

in youngtrees:
`Young Tree (middle)`
`Young Tree 2 (middle)`

### Capitalisation "loaded" *(edit: done)*
in poisonivy:
`[Poison Ivy] Loaded.`

in nature_classic:
`[Nature Classic] loaded!`

**Comment by Niklp09** [comment]
Logging part fixed by https://github.com/mt-mods/plantlife_modpack/pull/46
